#
default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=350', '--enforce-all']
        exclude: |
            (?x)^(
                docs/source-pytorch/_static/images/general/fast_2.gif|
                docs/source-pytorch/_static/images/mnist_imgs/pt_to_pl.jpg|
                docs/source-pytorch/_static/images/lightning_module/pt_to_pl.png|
                docs/source-pytorch/_static/images/general/pl_quick_start_full_compressed.gif|
                docs/source-pytorch/_static/images/general/pl_overview_flat.jpg|
                docs/source-pytorch/_static/images/general/pl_overview.gif|
                src/lightning_app/cli/pl-app-template/ui/yarn.lock|
                src/pytorch_lightning/CHANGELOG.md|
                src/lightning_lite/CHANGELOG.md
            )$
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        name: Upgrade code

  - repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=115, --wrap-descriptions=120]

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        name: Unused noqa

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: Format imports

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Format code
        exclude: docs/source-app

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        args: [--line-length=120]
        exclude: docs/source-app

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          #- mdformat-black
          - mdformat_frontmatter
        exclude: |
            (?x)^(
                src/pytorch_lightning/CHANGELOG.md|
                src/lightning_app/CHANGELOG.md|
                src/lightning_lite/CHANGELOG.md
            )$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
