[tool.poetry]
name = "rl-playground"
version = "0.1.0"
description = ""
authors = ["Taeho Lee <theodore.taeho.lee@gmail.com>"]
readme = "README.md"
packages = [{include = "rl_playground"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
